Basefunc
shulganew/gophermart pull request #1
Opened 2024-01-20 21:37 UTC by shulganew

2024-01-24 12:02 UTC, maxlyaptsev requested changes

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/model/status.go
> +type Status int
Если сделать статус стрингой (по сути получим енам) то это снимет довольно много сложностей ниже - все свитч кейсы станут не нужны
```suggestion
type Status string
```

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/storage/db.go
> +func NewRepo(ctx context.Context, master *pgx.Conn) (*RepoMarket, error) {
Предлагаю тут использовать готовые пакеты для транзакций - все таки sql внутри go не очень красиво и удобно
Вот один из самых популярных инструментов

https://github.com/pressly/goose

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/storage/db.go
> +		isPreorder BOOLEAN NOT NULL,
лучше использовать один формат - выше снейк кейс (user_id), а тут кемел кейс

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/storage/db.go
> +func (base *RepoMarket) Register(ctx context.Context, user model.User) error {
для базы данных не важен что контекст это регистрация (не факт что именно так будет использоваться этот метод, может быть это выгрузка из эксель со старого сайта)

```suggestion
func (base *RepoMarket) AddUser(ctx context.Context, user model.User) error {
```

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/storage/db.go
> +		return err
лучше взять такое правило: либо логируем ошибку, либо возвращаем. 
Если вернули ошибку - это ответственность кода выше решать что с ней делать. А так мы не даем выбора (грязные логи и дублирование ошибок в больших проектах это проблема)

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/storage/db.go
> +		INNER JOIN users ON orders.user_id = users.user_id
джойним юзера только чтобы получить user_id. Надо ли если он итак известен?
В целом хоть это и не по теме go - нужно избегать джойнов, это довольно ресурсоемкая операция и проектировать таблицы нужно так, чтобы минимизировать такие слияния

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/storage/db.go
> +		err = rows.Scan(&order.UserID, &order.Onumber, &order.Uploaded, &status, &used, &accrual)
Лучше создать отдельную структуру. Да, специфичную для этого запроса, DTO. Но можно использовать встраивание чтобы потом было проще поддерживать. Наличие большого количества переменных очень усложняет код

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/storage/db.go
> +	rows, err := base.master.Query(ctx, query, userID)
при использовании стандартной библиотеки нужно самостоятельно заботиться о закрытии потока. Рекомендую все же использовать https://github.com/jmoiron/sqlx
Код станет в разы проще и будет меньше ошибок

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/storage/db.go
> +func (base *RepoMarket) UpdateStatus(ctx context.Context, order *model.Order, accrual *decimal.Decimal) (err error) {
Тут несколько проблем:
1 - мы не должны требовать лишние данные. Для смены статуса достаточно знать номер заказа и его статус. Все остальное избыточно и запрашивать не нужно. В разных ситуациях может просто не быть этих лишних данных и их придется где-то брать, хотя они и не нужны. Плюс это добавляет больший объем в стек, что тоже не нужно

2 - метод называется "обновить статус" - это хорошо и правильно. Но неправильно при этом еще "заодно" бонусный счет изменять. Клиентский код об этом не подозревает, это скрытое и неочевидное поведение. Лучше сделать отдельную функцию рядом
```suggestion
func (base *RepoMarket) UpdateStatus(ctx context.Context, orderNr string, orderStatus string) (err error) {
```

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/storage/db.go
> +		INNER JOIN bonuses ON orders.onumber = bonuses.onumber;
я уже писал про лишние джойны, можно добавить недостающее поле, чтобы не запрашивать несколько таблиц

Но вообще тут в другом даже проблема - выборка никак не фильтруется, тут запрашивается сумма вообще всех бонусов

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/storage/db.go
> +		ORDER BY orders.uploaded DESC
та же проблема что и выше - нет фильтрации по userID и выбирается слишком много таблиц

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/storage/db.go
> +	for rows.Next() {
строки не закрываются. Тут и в остальных местах выше

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/config/ctxvalues.go
> +}
что-то это не имеет отношения ни к конфигу т.к. не является конфигурацией (пользователь меняется при каждом запросе) ни контекстом т.к. это и не контекст вовсе

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/storage/db.go
> +	}
В одном методе должен быть только один функционал

В целом тут лучше разделить db.go на несколько файлов чтобы такой путаницы не возникало - order.go / bonuses.go и т.п.

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/services/market.go
> +	err = m.stor.SetOrder(ctx, order.UserID, order.Onumber, isPreOrder, order.Bonus.Used)
```suggestion
	err = m.stor.AddOrder(ctx, order.UserID, order.Onumber, isPreOrder, order.Bonus.Used)
```
set не равно add. Есть существенное различие, set должен перезаписать состояние до переданного у существующего или не существующего заказа

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/services/market.go
> +			zap.S().Infoln("Order exist: ", order.Onumber)
Кажется не очень информативный info лог - "заказ существует", без контекста что это происходит при добавлении кажется что это нормальное поведение

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/services/market.go
> +func (m *Market) GetBalance(ctx context.Context, userID *uuid.UUID) (acc *decimal.Decimal, withdrawn *decimal.Decimal, err error) {
```suggestion
func (m *Market) GetBalance(ctx context.Context, userID *uuid.UUID) (int, error) {
```
баланс это какая-то конечная сумма. А не набор начислений и снятий

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/services/market.go
> +func (m *Market) CheckBalance(ctx context.Context, userID *uuid.UUID, amount *decimal.Decimal) (isEnough bool, err error) {
нет смысла все передавать ссылками - складывается ощущение что параметр опционален, да и в теле функции нужно тогда добавлять проверку на nil
```suggestion
func (m *Market) CheckBalance(ctx context.Context, userID uuid.UUID, amount decimal.Decimal) (isEnough bool, err error) {
```

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/services/market.go
> +	acc, err := m.stor.GetAccruals(ctx, userID)
по логике тут нужен баланс, а не только начисления. Т.к. денег с учетом списаний может быть меньше
```suggestion
	acc, err := m.stor.GetBalance(ctx, userID)
```

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/services/market.go
> +	}
какая-то инверсия получилась. Вместо проверки баланса проверяем бонусы. Даже если работает правильно, читать сложно

1. Получить начисления
2. Получить списания
3. Вычислить актуальный баланс
4. Сравнить с переданной суммой

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/services/market.go
> +	return
```suggestion
	return wds, err
```

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/services/observer.go
> +const UploadData = 3
это лучше унести в конфигурацию

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/services/observer.go
> +		if *status == 2 || *status == 3 {
лучше сделать константы для каждого статуса, человекочитаемые. И сравнивать с ними

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/services/observer.go
> +		if *status == 2 || *status == 3 {
```suggestion
		if order.status.isProcessed() ||  order.status.isInvalid() {
```

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/services/observer.go
> +type Observer struct {
не очень удачное название. Наблюдатель - а наблюдатель чего? AccrualFetcher/ AccrualUpdater?

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/services/observer.go
> +func (o *Observer) AddOreder(order *model.Order) {
```suggestion
func (o *Observer) AddOrder(order *model.Order) {
```
а что если передадим nil?

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/services/observer.go
> +	orders map[string]model.Order
а если у нас миллион заказов? Какой смысл копировать всю базу данных в мапу? У нас уже есть хранилище, нужно его использовать.

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/services/observer.go
> +func (o *Observer) getOrderStatus(order *model.Order) (status *model.Status, acc *decimal.Decimal, err error) {
нужно поработать над слоями. Есть клиент, транспортный слой - этот код нужно держать отдельно и не подмешивать туда локальные структуры. А есть код, который интерпретирует ответы и создает внутренние структуры

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/services/observer.go
> +func (o *Observer) getOrderStatus(order *model.Order) (status *model.Status, acc *decimal.Decimal, err error) {
```suggestion
func (o *Observer) getOrderStatus(order *model.Order) (accrualResponse, error) {
```
странный ответ функции из смеси статуса внутренний структуры и кастомного типа

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/services/register.go
> +	uuid, err := uuid.NewV7()
uuid может сгенерировать база данных при добавлении нового пользователя

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/services/register.go
> +	user.Password = hash
почему хеш становится паролем? Где правда?

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/services/register.go
> +func (r *Register) NewUser(ctx context.Context, user model.User) (userID *uuid.UUID, existed bool, err error) {
```suggestion
func (r *Register) AddUser(ctx context.Context, user model.User) (userID *uuid.UUID, err error) {
```
New используется чтобы показать что метод является конструктором
Существование пользователя не нужно возвращать отдельно - можно использовать ошибку для этого

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/services/register.go
> +func (r *Register) IsValid(ctx context.Context, untrusted *model.User) (userID *uuid.UUID, isValid bool) {
файл называется "регистрация" а по факту тут больше чем регистрация. Нужно либо вынести код, который не относится к регистрации в отдельные файлы, либо придумать более подходящее название

2024-01-24 12:02 UTC, maxlyaptsev commented on internal/api/handlers/orders.go
> +		isExistOther, err := u.market.IsExistForOtherUsers(req.Context(), userID, onumber)
```suggestion
		isExist, err := u.market.OrderExist(req.Context(), onumber)
```
В данном случае уже не важно кем был создан заказ. Поэтому фильтр лишний

2024-01-27 15:06 UTC, shulganew commented on internal/model/status.go
> +type Status int
Да, что-то я тут слишком сложно сделал, так намного проще все стало.

2024-01-28 15:48 UTC, shulganew commented on internal/storage/db.go
> +func NewRepo(ctx context.Context, master *pgx.Conn) (*RepoMarket, error) {
Перенес на goose.

2024-01-28 15:49 UTC, shulganew commented on internal/storage/db.go
> +		isPreorder BOOLEAN NOT NULL,
Оставил снейк для запросов, исправил на is_preorder

2024-01-28 15:55 UTC, shulganew commented on internal/storage/db.go
> +func (base *RepoMarket) Register(ctx context.Context, user model.User) error {
Понял, все методы относятся с storage и не тянут логику других слоев, исправил.

2024-01-30 17:37 UTC, shulganew commented on internal/storage/db.go
> +		return err
Понял, почистил все логи

2024-01-30 17:38 UTC, shulganew commented on internal/storage/db.go
> +		INNER JOIN users ON orders.user_id = users.user_id
Переделал структуру базы данных, удалось вообще все JOIN убрать

2024-01-30 17:38 UTC, shulganew commented on internal/storage/db.go
> +		err = rows.Scan(&order.UserID, &order.Onumber, &order.Uploaded, &status, &used, &accrual)
Решил с помощью библиотеки sqlx

2024-01-30 17:38 UTC, shulganew commented on internal/storage/db.go
> +	rows, err := base.master.Query(ctx, query, userID)
Перевел проект на sqlx

2024-01-30 17:39 UTC, shulganew commented on internal/storage/db.go
> +func (base *RepoMarket) UpdateStatus(ctx context.Context, order *model.Order, accrual *decimal.Decimal) (err error) {
Почистил методы на предмет передачи лишних параметров. Убрал скрытое поведение.

2024-01-30 17:40 UTC, shulganew commented on internal/storage/db.go
> +		INNER JOIN bonuses ON orders.onumber = bonuses.onumber;
Убрал лишние JOIN, все запросы теперь с выборокой.

2024-01-30 17:41 UTC, shulganew commented on internal/storage/db.go
> +		ORDER BY orders.uploaded DESC
JOIN убрал, везде сделал фильтрацию, в этом месте по пользователю.

2024-01-30 17:41 UTC, shulganew commented on internal/storage/db.go
> +	for rows.Next() {
sqlx решил эту проблему.

2024-01-30 17:42 UTC, shulganew commented on internal/config/ctxvalues.go
> +}
Убрал в модель, назвал MiddlwDTO, как дата трасфер объект для мидлвари.

2024-01-30 17:43 UTC, shulganew commented on internal/storage/db.go
> +	}
Да, это я просто не успел, разбил на файлы.

2024-01-30 17:43 UTC, shulganew commented on internal/services/market.go
> +	err = m.stor.SetOrder(ctx, order.UserID, order.Onumber, isPreOrder, order.Bonus.Used)
Запомнил, исправил.

2024-01-30 17:43 UTC, shulganew commented on internal/services/market.go
> +			zap.S().Infoln("Order exist: ", order.Onumber)
Стал стараться писать подробнее логи.

2024-01-30 17:54 UTC, shulganew commented on internal/services/market.go
> +func (m *Market) GetBalance(ctx context.Context, userID *uuid.UUID) (acc *decimal.Decimal, withdrawn *decimal.Decimal, err error) {
Разбил на два отдельных метода - получения начислений и списаний.

2024-01-30 17:55 UTC, shulganew commented on internal/services/market.go
> +func (m *Market) CheckBalance(ctx context.Context, userID *uuid.UUID, amount *decimal.Decimal) (isEnough bool, err error) {
Постарался убрать лишние ссылки

2024-01-30 17:56 UTC, shulganew commented on internal/services/market.go
> +	acc, err := m.stor.GetAccruals(ctx, userID)
Поправил логигу расчета бонусов, сделал отдельное поле в таблице пользователя и счтитаю все в нем.

2024-01-30 17:56 UTC, shulganew commented on internal/services/market.go
> +	}
Поправил логику.

2024-01-30 17:57 UTC, shulganew commented on internal/services/market.go
> +	return
Убрал лишние переменные в return'ах

2024-01-30 17:57 UTC, shulganew commented on internal/services/observer.go
> +const UploadData = 3
Перенес

2024-01-30 17:57 UTC, shulganew commented on internal/services/observer.go
> +		if *status == 2 || *status == 3 {
Исправил енум на стрингу, стало все адекватно.

2024-01-30 17:58 UTC, shulganew commented on internal/services/observer.go
> +type Observer struct {
Наблюдатель переделал в фетчера.

2024-01-30 17:58 UTC, shulganew commented on internal/services/observer.go
> +func (o *Observer) AddOreder(order *model.Order) {
Поработал с ссылками, убрал лишние

2024-01-30 17:58 UTC, shulganew commented on internal/services/observer.go
> +	orders map[string]model.Order
Убрал мапу вообще, сдел, как обсудили на 1:1

2024-01-30 17:59 UTC, shulganew commented on internal/services/observer.go
> +func (o *Observer) getOrderStatus(order *model.Order) (status *model.Status, acc *decimal.Decimal, err error) {
Перенес в api client, еще не очень уверен, что хороший вариант.

2024-01-30 17:59 UTC, shulganew commented on internal/services/register.go
> +	uuid, err := uuid.NewV7()
Сделал генерацию uuid с помощью postgers.

2024-01-30 18:00 UTC, shulganew commented on internal/services/register.go
> +	user.Password = hash
Сдалал отдельное поле для хеша, чтобы не путать. Это была плохая идея.

2024-01-30 18:00 UTC, shulganew commented on internal/services/register.go
> +func (r *Register) NewUser(ctx context.Context, user model.User) (userID *uuid.UUID, existed bool, err error) {
Сделал CreateUser

2024-01-30 18:01 UTC, shulganew commented on internal/services/register.go
> +func (r *Register) IsValid(ctx context.Context, untrusted *model.User) (userID *uuid.UUID, isValid bool) {
Назвал как maintenance, как поддрежка пользователя - регистрация, валидация, аутентификация и другое.

2024-01-30 18:01 UTC, shulganew commented on internal/api/handlers/orders.go
> +		isExistOther, err := u.market.IsExistForOtherUsers(req.Context(), userID, onumber)
Да, убрал, это лишнее.

2024-01-31 18:43 UTC, maxlyaptsev requested changes

2024-01-31 18:43 UTC, maxlyaptsev commented on internal/api/client/fetchacc.go
> +package client
файл лучше назвать accrual и тут держать все запросы к этому сервису

второе - нужно на уровень выше убрать, это не внутренее апи

2024-01-31 18:43 UTC, maxlyaptsev commented on internal/storage/market.go
> +package storage
Вопрос к неймингу. Относится и к этой директории и то же самое в сервисах увидел. У нас есть несколько сущностей. Какие-то могут быть объединены в одну, тут все по желанию

- order
- user
- balance
- accrual
- withdraw

Я бы скорее делал такие сущности:
- order
- user
- operations - операции - бонусы и снятие бонусов

Либо еще проще:

- user - здесь хранить и данные пользователя и баланс
- order - здесь хранить не только сам заказ, но и его начисление т.к. оно одно и списание т.к. оно тоже одно


В чем вопрос: 
я не очень понимаю что за сущности fetcher (получатель) maintenance (поддержка) и market (рынок)
Просто не понимаю логики разделения этих сущностей. И являются ли они сущностями. Для сервиса это еще можно было как-то объяснить, в репозитории не получается

2024-01-31 18:43 UTC, maxlyaptsev commented on internal/storage/db.go
> +
миграции лучше хранить в sql файлах, но хотя бы давай вынесем в отдельный файл, а тут только инициализацию оставим. А тем более рядом есть целый отдельный пакет - вот туда и нужно убрать

2024-01-31 18:43 UTC, maxlyaptsev commented on internal/services/maintenance.go
> +func NewRegister(stor Maintenancerer) *Maintenance {
тут не только регистрация. Давай назовем файл user.go и это будет userService
```suggestion
func NewUserService(stor Maintenancerer) *UserService {
```

2024-01-31 18:43 UTC, maxlyaptsev commented on internal/services/fetcher.go
> +func NewFetcher(stor FetcherUpdater, conf *config.Config) *Fetcher {
```suggestion
func NewAccrualService(
  orderRepo OrderRepository, 
  accrualClient AccrualClient, 
  conf *config.Config
) *Fetcher {
```
тут содержится логика обновления заказов с помощью сервиса accrual - давай так и назовем. Фетчер очень абстрактно - фетчить можно что угодно. Файлик можно назвать accrual.go

2024-01-31 18:43 UTC, maxlyaptsev commented on internal/services/maintenance.go
> +type Maintenancerer interface {
```suggestion
type UserRepository interface {
```

2024-01-31 18:43 UTC, maxlyaptsev commented on internal/services/fetcher.go
> +		accResp, err := client.FetchOrderStatus(order.OrderNr, o.conf)
клиент должен быть зависимостью этого сервиса, а не глобальным методом, мы вроде это обсуждали

2024-01-31 18:43 UTC, maxlyaptsev commented on internal/api/handlers/orders.go
> +		isPreorder, err := u.market.IsPreOrder(req.Context(), userID, orderNr)
мы выше выяснили что заказ есть. Теперь можем:
- получить заказ по его ID
- проверить что заказ не текущего пользователя order.ID != userID 
- аналогично сделать другие проверки не делая дополнительные запросы в бд

Еще лучше - первым делом проверить - а нет ли у нас заказа? И только если его нет пытаться добавить новый. Сейчас можно пойти таким сценарием что будет сделано 4 запроса в бд

2024-01-31 18:45 UTC, maxlyaptsev commented on internal/services/register.go
> +func (r *Register) IsValid(ctx context.Context, untrusted *model.User) (userID *uuid.UUID, isValid bool) {
Спорное название) Поддержка это про другое

2024-02-05 15:33 UTC, shulganew commented on internal/services/register.go
> +func (r *Register) IsValid(ctx context.Context, untrusted *model.User) (userID *uuid.UUID, isValid bool) {
Да, я тоже потом подумал, что неудачное. Сделал user

2024-02-05 15:33 UTC, shulganew commented on internal/api/client/fetchacc.go
> +package client
Исправил

2024-02-05 15:41 UTC, shulganew commented on internal/storage/market.go
> +package storage
Попробовал сделать нейминг более очеваидный, нарисовал диаграмму классов и поправил в проекте, обсудим 1:1 что можно еще сделать луше в проекте. https://miro.com/welcomeonboard/NVBHS1ZpVFVad2FZdXVUM2pPZWI0N0FUTjlFRThZYkJXbkFTM3JnaERxTFlVUEJWSXJhU1BLeHBRakZBVVVCU3wzNDU4NzY0NTc3NTQ4MjcxNjkwfDI=?share_link_id=180666047466

2024-02-05 15:43 UTC, shulganew commented on internal/storage/db.go
> +
Пока вынес в отдельный файл, я просто попробовал такой вариант для интереса, что так можно реализовать. А пример с файлами сделал в шортенере. Могу переделать в файлы, сделаю как лучше.

2024-02-05 15:43 UTC, shulganew commented on internal/services/maintenance.go
> +func NewRegister(stor Maintenancerer) *Maintenance {
Готово

2024-02-05 15:43 UTC, shulganew commented on internal/services/fetcher.go
> +func NewFetcher(stor FetcherUpdater, conf *config.Config) *Fetcher {
Готово

2024-02-05 15:44 UTC, shulganew commented on internal/services/maintenance.go
> +type Maintenancerer interface {
Готово

2024-02-05 15:44 UTC, shulganew commented on internal/services/fetcher.go
> +		accResp, err := client.FetchOrderStatus(order.OrderNr, o.conf)
Да, обсуждали, сейчас исправил, тоже хотел обсудить, где его разместить в проекте и как лучше реализовать.

2024-02-05 16:18 UTC, shulganew commented on internal/api/handlers/orders.go
> +		isPreorder, err := u.market.IsPreOrder(req.Context(), userID, orderNr)
Я тут думал таким образом, что большинство заказов прилетит корректными на ручку и быстрее будет его сразу добавить в базу, а если ловится ошибка duplicated, то уже по дереву. Попробовал переделать, не уверен, что исправил лучшим образом, давай обсудим на 1-1

2024-02-06 11:02 UTC, maxlyaptsev commented on migrations/20240127182854_tables.go
> +package migrations
вот сюда бы сами миграции тоже закинуть (они сейчас в cmd/tables)

2024-02-06 11:45 UTC, maxlyaptsev requested changes

2024-02-06 11:45 UTC, maxlyaptsev commented on internal/storage/db.go
> +func InitDB(ctx context.Context, conf *config.Config) (db *sqlx.DB, err error) {
Вот тут хочется отделить инциализацию базы данных от репозиториев. База данных (коннект) должен быть просто зависимостью

2024-02-06 11:45 UTC, maxlyaptsev commented on internal/accrual/fetch.go
> +package accrual
тоже является сервисом

2024-02-06 13:39 UTC, shulganew commented on internal/storage/db.go
> +func InitDB(ctx context.Context, conf *config.Config) (db *sqlx.DB, err error) {
Перенес в пакет app

2024-02-06 13:42 UTC, shulganew commented on migrations/20240127182854_tables.go
> +package migrations
Готово, перенес.

2024-02-06 14:05 UTC, maxlyaptsev commented on internal/app/init.go
> +	calcSrv := services.NewCalcService(stor)
app/container.go

type Container struct {
    db *pg.Sql
    accrual AccrualClient
}

func initDB() {
container.db = pg.Connect()
}
func getDB() {
return container.db
}

container.accrual = accrual.NewAccrualClient(conf)

accSrv := services.NewAccrualService(container.GetAccrual(), )

2024-02-06 14:08 UTC, maxlyaptsev commented on cmd/gophermart/main.go
> +	if err := http.ListenAndServe(conf.Address, router.RouteMarket(conf, calcSrv, userSrv, accSrv, orderSrv)); err != nil {
```suggestion
	if err := http.ListenAndServe(conf.Address, router.RouteMarket(app)); err != nil {
```

2024-02-06 14:15 UTC, maxlyaptsev commented on cmd/gophermart/main.go
> +	calcSrv, userSrv, accSrv, orderSrv := app.InitApp(ctx, conf, db)
```suggestion
	app.Start(ctx, conf)
```

2024-02-06 14:28 UTC, maxlyaptsev commented on internal/config/config.go
> +	config.Migrations = *isMigrations
решили выпилить миграцию из кода и оставить только sql файлы, которые будут запускаться через cli

2024-02-07 13:43 UTC, shulganew commented on cmd/gophermart/main.go
> +	if err := http.ListenAndServe(conf.Address, router.RouteMarket(conf, calcSrv, userSrv, accSrv, orderSrv)); err != nil {
Исправил, реализовал через паттерн container

2024-02-07 13:57 UTC, shulganew commented on cmd/gophermart/main.go
> +	calcSrv, userSrv, accSrv, orderSrv := app.InitApp(ctx, conf, db)
Я оставил Init, у меня не получилось убрать запуск сервера в приложение. App использует router, когда запускает сервер, а router использует App. Получаю циклическую зависимость. Тоже при попытке сделать перенос конфига в App, попробовал разные варианты, всегда получаю циклическую зависимось либо с конфигом, либо с сервисами.

2024-02-07 13:57 UTC, shulganew commented on internal/config/config.go
> +	config.Migrations = *isMigrations
Выпилил, добавил в workflow, все хорошо.

2024-02-07 21:42 UTC, maxlyaptsev commented on internal/app/container.go
> +func (c *Application) GetCalculationService() *services.CalculationService {
я сам ввел в заблуждение - в go не принято добавлять get, т.е. просто обращаемся как к полю структуры
```suggestion
func (c *Application) CalculationService() *services.CalculationService {
```

2024-02-07 21:42 UTC, maxlyaptsev commented on terq
> +
а что это за файл?)

2024-02-07 21:47 UTC, maxlyaptsev commented on cmd/gophermart/main.go
> +	calcSrv, userSrv, accSrv, orderSrv := app.InitApp(ctx, conf, db)
можно тогда попробовать убрать  как-то так:
- app/config/confgi.go 
- app/server/server.go

2024-02-07 21:52 UTC, maxlyaptsev commented on internal/ports/storage/order.go
> +func (r *Repo) AddOrder(ctx context.Context, userID uuid.UUID, order string, isPreOrder bool, withdrawn decimal.Decimal) error {
```suggestion
func (r *Repo) AddOrder(ctx context.Context, data entities.AddOrder) error {
```
лучше не оставлять большое количество аргументов - можно упаковать их в одну DTO

2024-02-08 13:21 UTC, shulganew commented on terq
> +
) удалил

2024-02-08 14:13 UTC, merged